server:
  port: 7000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://119.91.20.118:3306/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
#        注册中心地址
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
  application:
    name: mall-coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto